thread_example1:	 thread_example1.o
    /usr/bin/c++ -std=c++11 -lpthread thread_example1.o -o thread_example

thread_example1.o:	thread_example1.cpp
    /usr/bin/c++ -c -std=c++11  thread_example1.cpp

clean: 	
	rm *.o
