compile_example:    my_math.o compile_example.o
	g++ -o compile_example my_math.o compile_example.o

my_math.o:  my_math.cpp
	g++ -c my_math.cpp

compile_example.o:  compile_example.cpp
	g++ -c compile_example.cpp
